


def convert_exception_to_response(get_response):
    pass
